### PR TITLE
Fix: Update with the new utility API

### LINKED ISSUE #37: Bug: Update codebase for new utility API
## Context
The `utility` library introduced breaking API changes.
Parts of the codebase still rely on the old `utility` API, which can lead to build failures or inconsistent behavior.

## Expected behavior
The project should compile and run using the latest `utility` API without deprecation warnings or runtime issues.

## Tasks
- Identify all usages of the old `utility` API across the codebase.
- Update these call sites to the new `utility` API.
- Run the test suite and samples to confirm everything still behaves as expected.
- Update any relevant documentation if the public-facing behavior or signatures changed.

### PR DESCRIPTION
**Pull request by clement-antoine-xavier**

### CODE REVIEW

File: headers/guillaume/systems/rectangle_render.hpp [hunk 1]
```diff
@@ -65,9 +63,7 @@ namespace guillaume::systems
 													 float sy, float sizeX,
 													 float sizeY, float radius,
 													 int arcSegments = 16);
-		static Vertex
-			createVertex(const Vec2 &pos,
-						 const utility::graphics::Color<uint8_t> &color);
+		static Vertex createVertex(const Vec2 &pos, const utility::graphics::Color32Bit &color);
```
Comment (ju-lit-hein) [inline headers/guillaume/systems/rectangle_render.hpp]: You need to document these methods. @clement-antoine-xavier

**Review by ju-lit-hein — CHANGES_REQUESTED** [review]

File: headers/guillaume/ecs/system.hpp [hunk 2]
```diff
@@ -52,6 +54,7 @@ namespace guillaume::ecs
 	{
 		private:
 		Entity::Signature _signature;	 ///< System signature
+		ecs::ComponentRegistry *_activeComponentRegistry { nullptr };
```
Comment (ju-lit-hein) [inline headers/guillaume/ecs/system.hpp]: Missing documentation on this class member

**Review by ju-lit-hein — CHANGES_REQUESTED** [review]
The class member `Guillaume::ecs::System::_activeComponentRegistry` need to be documented @clement-antoine-xavier

**Review by ju-lit-hein — APPROVED** [review]

**Comment by ju-lit-hein** [comment]
Good job! 👍
